# Build stage

FROM maven:3.8.5-openjdk-17 AS build
COPY pom.xml /app/
COPY src /app/src
RUN mvn -f /app/pom.xml clean package -DskipTests

# Run stage
FROM eclipse-temurin:17-jre AS run
ARG JAR_FILE=/app//target/*.jar
COPY --from=build ${JAR_FILE} /app.jar
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=render-prod", "/app.jar"]
